NEW_ACCOUNT_POPUP_TITLE = '创建账号'
NEW_ACCOUNT_POPUP_CONTENT = '是否确认创建账号？'
NEW_ACCOUNT_POPUP_SUCCEED = '注册成功'

RESET_PASSWORD_POPUP_TITLE = '修改密码'
RESET_PASSWORD_POPUP_CONTENT = '是否确认修改密码？'

EMPTY_ACCOUNT = '没有输入账号'
EMPTY_PASSWORD = '没有输入密码'
CONSISTENT_PASSWORD = '两次密码相同'
INCONSISTENT_PASSWORD = '两次密码不相同'

SERVER_ITEM = '服务器'
SERVER_SITUATION = '状态'
CANT_ENTER_SERVER = '无法连接服务器'
SELECT_SERVER = '请选择服务器'
SERVER_SITUATION_NORMAL = '流畅'
SERVER_SITUATION_BUSY = '拥挤'
SERVER_SITUATION_STOP = '暂停'