# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(900, 600))
        MainWindow.setMaximumSize(QtCore.QSize(900, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ServerWidget = QtWidgets.QListWidget(self.centralwidget)
        self.ServerWidget.setGeometry(QtCore.QRect(29, 69, 301, 491))
        self.ServerWidget.setObjectName("ServerWidget")
        self.Serverlabel = QtWidgets.QLabel(self.centralwidget)
        self.Serverlabel.setGeometry(QtCore.QRect(29, 20, 301, 40))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.Serverlabel.setFont(font)
        self.Serverlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Serverlabel.setObjectName("Serverlabel")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(360, 20, 520, 471))
        self.listWidget.setObjectName("listWidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(360, 520, 521, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(23)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LoginButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.LoginButton.setFont(font)
        self.LoginButton.setObjectName("LoginButton")
        self.horizontalLayout.addWidget(self.LoginButton)
        self.ResetButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.ResetButton.setFont(font)
        self.ResetButton.setObjectName("ResetButton")
        self.horizontalLayout.addWidget(self.ResetButton)
        self.RegisterButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.RegisterButton.setFont(font)
        self.RegisterButton.setObjectName("RegisterButton")
        self.horizontalLayout.addWidget(self.RegisterButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "超神冒险岛登录器"))
        self.Serverlabel.setText(_translate("MainWindow", "服务器列表"))
        self.LoginButton.setText(_translate("MainWindow", "登录服务器"))
        self.ResetButton.setText(_translate("MainWindow", "修改密码"))
        self.RegisterButton.setText(_translate("MainWindow", "注册账号"))
