# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewAccount.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewAccountWidget(object):
    def setupUi(self, NewAccountWidget):
        NewAccountWidget.setObjectName("NewAccountWidget")
        NewAccountWidget.resize(600, 450)
        NewAccountWidget.setMinimumSize(QtCore.QSize(600, 450))
        NewAccountWidget.setMaximumSize(QtCore.QSize(600, 450))
        NewAccountWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/图标/MapleStory.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NewAccountWidget.setWindowIcon(icon)
        self.ReturnButton = QtWidgets.QPushButton(NewAccountWidget)
        self.ReturnButton.setGeometry(QtCore.QRect(350, 370, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.ReturnButton.setFont(font)
        self.ReturnButton.setObjectName("ReturnButton")
        self.layoutWidget = QtWidgets.QWidget(NewAccountWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 40, 501, 180))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(23)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Account = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.Account.setFont(font)
        self.Account.setObjectName("Account")
        self.horizontalLayout.addWidget(self.Account)
        self.AccountEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.AccountEdit.setFont(font)
        self.AccountEdit.setObjectName("AccountEdit")
        self.horizontalLayout.addWidget(self.AccountEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.NewPassword = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.NewPassword.setFont(font)
        self.NewPassword.setObjectName("NewPassword")
        self.horizontalLayout_3.addWidget(self.NewPassword)
        self.NewPasswordEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.NewPasswordEdit.setFont(font)
        self.NewPasswordEdit.setObjectName("NewPasswordEdit")
        self.horizontalLayout_3.addWidget(self.NewPasswordEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.ConfirmButton = QtWidgets.QPushButton(NewAccountWidget)
        self.ConfirmButton.setGeometry(QtCore.QRect(50, 370, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.ConfirmButton.setFont(font)
        self.ConfirmButton.setDefault(True)
        self.ConfirmButton.setObjectName("ConfirmButton")

        self.retranslateUi(NewAccountWidget)
        QtCore.QMetaObject.connectSlotsByName(NewAccountWidget)

    def retranslateUi(self, NewAccountWidget):
        _translate = QtCore.QCoreApplication.translate
        NewAccountWidget.setWindowTitle(_translate("NewAccountWidget", "注册账号"))
        self.ReturnButton.setText(_translate("NewAccountWidget", "返回"))
        self.Account.setText(_translate("NewAccountWidget", "新账号"))
        self.NewPassword.setText(_translate("NewAccountWidget", "新密码"))
        self.ConfirmButton.setText(_translate("NewAccountWidget", "确认注册"))
